ifdef::env-github[]
:imagesdir: images/
endif::[]
:imagesdir: images

== Simple Time

The exercise for the first week is an appetizer before we start with the real work, "the dinner". Goal of the assignment
is to get familiar with our way of working using an external API by describing the requirements and a Factory class, as part of
your implementation, that creates instances of the classes that implement the API. 

The API is published in the Maven central repository:
https://central.sonatype.com/artifact/io.github.fontysvenlo.alda/simpletime_api/2.5

The JavaDoc is published on https://fontysvenlo.github.io/alda_simpletime_api/v2.5/simpletimeapi/module-summary.html

The main exercise for the first seven weeks will be about an appointment planning tool to schedule appointments. As you can imagine,
Time and Duration play an important role in such an application. Dealing with dates and times is always a bit awkward. Even in Java,
it took a long time (since Java8) before a decent Date and Time API (`java.time`) was available. It's an extensive API that needs some studying
for proper use.

Normally you shouldn't reinvent the wheel, but this week we do by developing our own simple and stupid `Time` and `Duration` classes.
We purposely do not use the `java.time` API. You'll be provided with a Maven project that contains a reference to the API (simpletimeapi) and a Service
Finder facility already. In your test classes, you can invoke the static `getFactory()` method of the `ServiceFinder` (see test package) class to get an
`AbstractSimpleTimeFactory` object that in turn can create `Time` and `Duration` objects. 
See the class diagram below.

.Class diagram for the classes Time and Duration.
image::simpletimecd.svg[]


== Tasks

Read the JavaDoc published on:
https://fontysvenlo.github.io/alda_simpletime_api/v2.5/simpletimeapi/module-summary.html

Open the provided project in your IDE. You'll probably need to build the project first, in order to download Maven dependencies.

Based on this api, Test-Driven develop your implementations of the types:

. SimpleTimeFactory

. Time

. Duration

Make sure that the test coverage is 100 percent, using the already available *JacoCoverage* plugin (as it was available in PRC2). Write only code that is needed for your tests to succeed. That way you will keep your code coverage at 100% automatically. 

Our teacher tests are just a final check. First try to fully test and implement the required functionality. Commit on a regular base, but only push your solution to Github at the moment you think you completely solved the assignment. Your task is not finished as long as there are red tests in either YOUR or OUR test runs and as long as the coverage of YOUR tests on YOUR code is on the required (CodeGrade) level.
