services:
  github-actions-runner:
    image: evl8/esd-github-actions-runner
    environment:
      - URL=value
      - TOKEN=value
    networks:
      - esd
  nexus:
    image: sonatype/nexus:oss 
    ports:
    - "8081:8081"
    networks:
      - esd
networks:
  esd:
    driver: bridge